* [32mmaster[m
  [31mremotes/origin/21[m
  [31mremotes/origin/24[m
  [31mremotes/origin/Barra-de-Busca-Req-13-ao-18[m
  [31mremotes/origin/Explorar-por-ingredientes-Reqs-75-76-77[m
  [31mremotes/origin/Explorar-por-local-de-origem[m
  [31mremotes/origin/Explore-Drink-meals-Reqs-70-71-72-73-74[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/Header-Req-9-ao-12[m
  [31mremotes/origin/Menu-inferior[m
  [31mremotes/origin/Teste-Receitas-feitas[m
  [31mremotes/origin/app-receitas[m
  [31mremotes/origin/cards-css-merged-bugfix[m
  [31mremotes/origin/explore-page[m
  [31mremotes/origin/first-mock-test[m
  [31mremotes/origin/gh-pages[m
  [31mremotes/origin/group-1[m
  [31mremotes/origin/group-1-profilePage[m
  [31mremotes/origin/group-13-altera-require[m
  [31mremotes/origin/group-13-css[m
  [31mremotes/origin/group-13-detail-exclude-test[m
  [31mremotes/origin/group-13-explore-screens[m
  [31mremotes/origin/group-13-explorer-ingredients-and-others[m
  [31mremotes/origin/group-13-individual-details[m
  [31mremotes/origin/group-13-recipe-detail[m
  [31mremotes/origin/group-14/DoneRecipes[m
  [31mremotes/origin/group-14/requisito-10[m
  [31mremotes/origin/group-14/requisito-20[m
  [31mremotes/origin/group-14/requisito-33[m
  [31mremotes/origin/group-14/requisito-54[m
  [31mremotes/origin/group-15-recipedetails[m
  [31mremotes/origin/group-15-ygor[m
  [31mremotes/origin/group-15-ygor2[m
  [31mremotes/origin/group-15-ygor3[m
  [31mremotes/origin/group-15-ygor4[m
  [31mremotes/origin/group-17-explore-by-area[m
  [31mremotes/origin/group-17-explore-by-ingredient[m
  [31mremotes/origin/group-17-header-search-bar[m
  [31mremotes/origin/group-17-localStorage[m
  [31mremotes/origin/group-17-mealsBody[m
  [31mremotes/origin/group-20-details[m
  [31mremotes/origin/group-20-details-page[m
  [31mremotes/origin/group-20-details-page-47[m
  [31mremotes/origin/group-20-explorar[m
  [31mremotes/origin/group-20-explorar-origin[m
  [31mremotes/origin/group-20-login-page[m
  [31mremotes/origin/group-20-newDetails[m
  [31mremotes/origin/group-20-profile-page[m
  [31mremotes/origin/group-20-send-initial[m
  [31mremotes/origin/group-22-email-senha-botao[m
  [31mremotes/origin/group-6-carousel[m
  [31mremotes/origin/group-6-css[m
  [31mremotes/origin/group-6-page-details[m
  [31mremotes/origin/group-6-page-progress-recipe[m
  [31mremotes/origin/group-6-resolve-problems[m
  [31mremotes/origin/group-8-done-recipes[m
  [31mremotes/origin/group-8-receitas-feitas-bug[m
  [31mremotes/origin/group-requirements-13-to-18[m
  [31mremotes/origin/group14-req25[m
  [31mremotes/origin/group17-mealsBody[m
  [31mremotes/origin/grupo-12-requisito54[m
  [31mremotes/origin/grupo-8-css[m
  [31mremotes/origin/grupo-8-css-login-teste[m
  [31mremotes/origin/grupo-8-header[m
  [31mremotes/origin/grupo-8-tela-detalhes[m
  [31mremotes/origin/header-group-21[m
  [31mremotes/origin/joao-searchbar-group-15[m
  [31mremotes/origin/jose-breno-projeto-app-receita-67,68,69[m
  [31mremotes/origin/kevinEthisouza-maingroup-9[m
  [31mremotes/origin/login-page[m
  [31mremotes/origin/loloopes-patch-1[m
  [31mremotes/origin/main[m
  [31mremotes/origin/main-group-04[m
  [31mremotes/origin/main-group-1[m
  [31mremotes/origin/main-group-1-R17[m
  [31mremotes/origin/main-group-1-R33-a-R40[m
  [31mremotes/origin/main-group-1-css[m
  [31mremotes/origin/main-group-1-em-progresso-parte2[m
  [31mremotes/origin/main-group-1-header[m
  [31mremotes/origin/main-group-1-start[m
  [31mremotes/origin/main-group-10[m
  [31mremotes/origin/main-group-10-Style[m
  [31mremotes/origin/main-group-10-Testes90Porcento[m
  [31mremotes/origin/main-group-10-search-bar[m
  [31mremotes/origin/main-group-10-testsFooter[m
  [31mremotes/origin/main-group-11[m
  [31mremotes/origin/main-group-11-Tesr-Foods-Explorer[m
  [31mremotes/origin/main-group-11-Teste-Footer[m
  [31mremotes/origin/main-group-11-cria-tela-principal-de-receitas[m
  [31mremotes/origin/main-group-11-explore[m
  [31mremotes/origin/main-group-11-explore-full[m
  [31mremotes/origin/main-group-11-full-header[m
  [31mremotes/origin/main-group-11-hotfix[m
  [31mremotes/origin/main-group-11-list[m
  [31mremotes/origin/main-group-11-receitapronta[m
  [31mremotes/origin/main-group-11-tela-de-explorar-drinks[m
  [31mremotes/origin/main-group-11-tela-de-explorar-principal[m
  [31mremotes/origin/main-group-11-tela-de-perfil[m
  [31mremotes/origin/main-group-11-teladetalhes-2[m
  [31mremotes/origin/main-group-12[m
  [31mremotes/origin/main-group-12-create-context[m
  [31mremotes/origin/main-group-12-css-alan[m
  [31mremotes/origin/main-group-12-explorer-food-or-drinks-page[m
  [31mremotes/origin/main-group-12-explorer-page[m
  [31mremotes/origin/main-group-12-footer-requisito-9[m
  [31mremotes/origin/main-group-12-header-component[m
  [31mremotes/origin/main-group-12-search-bar-component[m
  [31mremotes/origin/main-group-12-tela-principal-atual[m
  [31mremotes/origin/main-group-12-tela-principal-receita[m
  [31mremotes/origin/main-group-13[m
  [31mremotes/origin/main-group-13-evaluator[m
  [31mremotes/origin/main-group-13-fix-linter[m
  [31mremotes/origin/main-group-13-login-css-styleshee[m
  [31mremotes/origin/main-group-14[m
  [31mremotes/origin/main-group-14-arrumando-requisitos[m
  [31mremotes/origin/main-group-14-criacao-rotas[m
  [31mremotes/origin/main-group-14-req-14-18[m
  [31mremotes/origin/main-group-14-tela-de-login[m
  [31mremotes/origin/main-group-15[m
  [31mremotes/origin/main-group-15-bugfix[m
  [31mremotes/origin/main-group-15-favorite-recipes[m
  [31mremotes/origin/main-group-15-styles[m
  [31mremotes/origin/main-group-16[m
  [31mremotes/origin/main-group-16-reducingcomplexity[m
  [31mremotes/origin/main-group-16-req-47-53[m
  [31mremotes/origin/main-group-17[m
  [31mremotes/origin/main-group-17-Explore[m
  [31mremotes/origin/main-group-17-recipe-details[m
  [31mremotes/origin/main-group-18[m
  [31mremotes/origin/main-group-18-localStorage[m
  [31mremotes/origin/main-group-18-req-81[m
  [31mremotes/origin/main-group-18-req33[m
  [31mremotes/origin/main-group-18-req33-34-att[m
  [31mremotes/origin/main-group-18-req47[m
  [31mremotes/origin/main-group-18-req54areq59[m
  [31mremotes/origin/main-group-18-tests[m
  [31mremotes/origin/main-group-19[m
  [31mremotes/origin/main-group-19-correção-comidas-bebidas[m
  [31mremotes/origin/main-group-19-css-login[m
  [31mremotes/origin/main-group-19-reuisito-13[m
  [31mremotes/origin/main-group-2[m
  [31mremotes/origin/main-group-2-Explore.test[m
  [31mremotes/origin/main-group-2-ReceitasFeitas-parte1[m
  [31mremotes/origin/main-group-2-css[m
  [31mremotes/origin/main-group-2-css-parte-1[m
  [31mremotes/origin/main-group-2-refatoracao-mari[m
  [31mremotes/origin/main-group-20[m
  [31mremotes/origin/main-group-21[m
  [31mremotes/origin/main-group-21-Estilizando_CSS[m
  [31mremotes/origin/main-group-21-Teste_Page_NotFound[m
  [31mremotes/origin/main-group-22[m
  [31mremotes/origin/main-group-22-Header[m
  [31mremotes/origin/main-group-22-Header-req9[m
  [31mremotes/origin/main-group-22-TelasMatheus[m
  [31mremotes/origin/main-group-22-css-genesis[m
  [31mremotes/origin/main-group-22-css-header[m
  [31mremotes/origin/main-group-22-css-login[m
  [31mremotes/origin/main-group-22-estruturacao[m
  [31mremotes/origin/main-group-22-favorites[m
  [31mremotes/origin/main-group-22-lintErrorsLoginAndHeader[m
  [31mremotes/origin/main-group-22-login[m
  [31mremotes/origin/main-group-22-login-6-8[m
  [31mremotes/origin/main-group-22-main-recipes-screen[m
  [31mremotes/origin/main-group-22-profile[m
  [31mremotes/origin/main-group-22-searchBar[m
  [31mremotes/origin/main-group-23[m
  [31mremotes/origin/main-group-23-RecipesMaking[m
  [31mremotes/origin/main-group-23-css-styling[m
  [31mremotes/origin/main-group-23-requirement-01[m
  [31mremotes/origin/main-group-23-requisito-19-20[m
  [31mremotes/origin/main-group-23-requisitos-75-77[m
  [31mremotes/origin/main-group-23-requisitos-9-11[m
  [31mremotes/origin/main-group-24[m
  [31mremotes/origin/main-group-24-style[m
  [31mremotes/origin/main-group-24-tela-detalhes[m
  [31mremotes/origin/main-group-25[m
  [31mremotes/origin/main-group-25-comidas-feitas[m
  [31mremotes/origin/main-group-25-css[m
  [31mremotes/origin/main-group-25-explore-food[m
  [31mremotes/origin/main-group-26[m
  [31mremotes/origin/main-group-26-css[m
  [31mremotes/origin/main-group-27[m
  [31mremotes/origin/main-group-27-Corrigindo-Requisitos[m
  [31mremotes/origin/main-group-27-css[m
  [31mremotes/origin/main-group-27-ex44[m
  [31mremotes/origin/main-group-27-ex64[m
  [31mremotes/origin/main-group-27-ex65[m
  [31mremotes/origin/main-group-27-ex651[m
  [31mremotes/origin/main-group-27-footer-tests[m
  [31mremotes/origin/main-group-27-recipes-in-progress[m
  [31mremotes/origin/main-group-27-test[m
  [31mremotes/origin/main-group-3[m
  [31mremotes/origin/main-group-3-css[m
  [31mremotes/origin/main-group-3-detalhes-receitas-botao-iniciar[m
  [31mremotes/origin/main-group-3-login[m
  [31mremotes/origin/main-group-3-profile-page-parte-2[m
  [31mremotes/origin/main-group-3-receitas-feitas[m
  [31mremotes/origin/main-group-3-req-17[m
  [31mremotes/origin/main-group-3-req-29[m
  [31mremotes/origin/main-group-3-req47-53[m
  [31mremotes/origin/main-group-3-requisito-28[m
  [31mremotes/origin/main-group-4[m
  [31mremotes/origin/main-group-4-css[m
  [31mremotes/origin/main-group-4-done-recipes[m
  [31mremotes/origin/main-group-4-explore-ingredients[m
  [31mremotes/origin/main-group-4-explore-requisito-77[m
  [31mremotes/origin/main-group-4-favorite-icon[m
  [31mremotes/origin/main-group-5[m
  [31mremotes/origin/main-group-5-enfim-css[m
  [31mremotes/origin/main-group-6[m
  [31mremotes/origin/main-group-7[m
  [31mremotes/origin/main-group-7-explorar-local[m
  [31mremotes/origin/main-group-7-footer[m
  [31mremotes/origin/main-group-7-recipelist2[m
  [31mremotes/origin/main-group-7-recipelist3[m
  [31mremotes/origin/main-group-7-recipes-list31[m
  [31mremotes/origin/main-group-7-recipes-list33[m
  [31mremotes/origin/main-group-7-requisito-1[m
  [31mremotes/origin/main-group-7-searchBar[m
  [31mremotes/origin/main-group-7-tela-explorar-bebidas-comidas[m
  [31mremotes/origin/main-group-8[m
  [31mremotes/origin/main-group-8-initial-state[m
  [31mremotes/origin/main-group-8-resolvendo-conflitos[m
  [31mremotes/origin/main-group-9[m
  [31mremotes/origin/main-group-9-APIs[m
  [31mremotes/origin/main-group-9-DetailsPage-Requisito-36e41[m
  [31mremotes/origin/main-group-9-HomePage[m
  [31mremotes/origin/main-group-9-RTL[m
  [31mremotes/origin/main-group-9-Refatoracao[m
  [31mremotes/origin/main-group-9-explore[m
  [31mremotes/origin/main-group-9-exploreFood/exploreDrink[m
  [31mremotes/origin/main-group-9-exploreInfredient[m
  [31mremotes/origin/main-group-9-menuInferior[m
  [31mremotes/origin/main-group-9-req-51[m
  [31mremotes/origin/main-group-9-req-53[m
  [31mremotes/origin/main-group-9-req75-77[m
  [31mremotes/origin/main-group-9-styled-login-cards[m
  [31mremotes/origin/master[m
  [31mremotes/origin/mian-group-1[m
  [31mremotes/origin/pedrobritobr-patch-1[m
  [31mremotes/origin/profile-page[m
  [31mremotes/origin/profile-pages[m
  [31mremotes/origin/recipe-app[m
  [31mremotes/origin/recipes-app-master[m
  [31mremotes/origin/requirements-70-to-74[m
  [31mremotes/origin/requisito-33-ao-38-group-21-rafael[m
  [31mremotes/origin/requisitos-13-ao-18-rafaelromano-group-21[m
  [31mremotes/origin/requisitos-component-made[m
  [31mremotes/origin/requisitos67-74[m
  [31mremotes/origin/requisitos67-74nova[m
  [31mremotes/origin/requisitos67-74novamente[m
  [31mremotes/origin/revert-129-main-group-12-footer-requisito-9[m
  [31mremotes/origin/revert-379-main-group-7-recipelist2[m
  [31mremotes/origin/revert-564-main-group-18-req39[m
  [31mremotes/origin/revert-638-group-13-css[m
  [31mremotes/origin/revert-671-grupo-8-css-login-teste[m
  [31mremotes/origin/revert-714-main-group-12-Css-gu[m
  [31mremotes/origin/rod-group-26-done-recipes[m
  [31mremotes/origin/tryber/sd-013-b-project-recipes-app-Pull-Request-181[m
